-- PostgreSQL: conecte-se previamente à base academia_semana_03.
BEGIN;

CREATE TABLE aluno (
    id_aluno INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf CHAR(11) NOT NULL UNIQUE,
    data_nascimento DATE NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    data_cadastro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_aluno_email CHECK (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'),
    CONSTRAINT ck_aluno_cpf CHECK (cpf ~ '^[0-9]{11}$'),
    CONSTRAINT ck_aluno_nascimento CHECK (data_nascimento <= CURRENT_DATE)
);

CREATE TABLE instrutor (
    id_instrutor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf CHAR(11) NOT NULL UNIQUE,
    especialidade VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    data_contratacao DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT ck_instrutor_email CHECK (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'),
    CONSTRAINT ck_instrutor_cpf CHECK (cpf ~ '^[0-9]{11}$')
);

CREATE TABLE plano (
    id_plano INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE assinatura (
    id_assinatura INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_aluno INTEGER NOT NULL,
    id_plano INTEGER NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE,
    status TEXT NOT NULL DEFAULT 'ATIVA',
    forma_pagamento TEXT NOT NULL,
    CONSTRAINT ck_assinatura_periodo CHECK (data_fim IS NULL OR data_fim >= data_inicio),
    CONSTRAINT ck_assinatura_status CHECK (status IN ('ATIVA', 'INATIVA', 'CANCELADA')),
    CONSTRAINT ck_assinatura_pagamento CHECK (forma_pagamento IN ('CARTAO', 'PIX', 'DINHEIRO', 'BOLETO')),
    CONSTRAINT fk_assinatura_aluno FOREIGN KEY (id_aluno) REFERENCES aluno(id_aluno),
    CONSTRAINT fk_assinatura_plano FOREIGN KEY (id_plano) REFERENCES plano(id_plano)
);

CREATE TABLE aula (
    id_aula INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_instrutor INTEGER NOT NULL,
    CONSTRAINT fk_aula_instrutor FOREIGN KEY (id_instrutor) REFERENCES instrutor(id_instrutor)
);

CREATE TABLE participa (
    id_aluno INTEGER NOT NULL,
    id_aula INTEGER NOT NULL,
    PRIMARY KEY (id_aluno, id_aula),
    CONSTRAINT fk_participa_aluno FOREIGN KEY (id_aluno) REFERENCES aluno(id_aluno),
    CONSTRAINT fk_participa_aula FOREIGN KEY (id_aula) REFERENCES aula(id_aula)
);

-- Índices para junções e filtros iniciados pelas FKs. PostgreSQL não os cria
-- automaticamente ao declarar uma chave estrangeira.
CREATE INDEX idx_assinatura_id_aluno ON assinatura(id_aluno);
CREATE INDEX idx_assinatura_id_plano ON assinatura(id_plano);
CREATE INDEX idx_aula_id_instrutor ON aula(id_instrutor);
CREATE INDEX idx_participa_id_aula ON participa(id_aula);

COMMIT;
